import { Linking, Pressable, ScrollView, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '@/components/ui/Screen';
import { Container } from '@/components/ui/Container';
import { Card } from '@/components/ui/Card';
import { useThemeColors } from '@/hooks/useTheme';

const PRIVACY_URL = 'https://tsutsu03.github.io/kwagi-app/privacy/';
const SUPPORT_URL = 'https://tsutsu03.github.io/kwagi-app/support/';

export default function LegalScreen() { const c = useThemeColors(); return <Screen rail={false}><View className="flex-row items-center border-b border-bordersoft p-4"><Pressable onPress={() => router.back()} accessibilityRole="button" accessibilityLabel="Back" className="h-11 w-11 items-center justify-center"><Ionicons name="chevron-back" size={26} color={c.sub} /></Pressable><Text className="ml-1 text-md font-bold text-ink">Privacy and disclaimer</Text></View><ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 40 }}><Container><Card className="mb-4"><Text className="text-lg font-bold text-ink">Privacy summary</Text><Text className="mt-2 text-sm leading-6 text-sub">Kwagi stores your profile, notes, flashcards, quiz history, and preferences locally on your device. You do not need an account. Kwagi does not send this data to a Kwagi server. Data leaves the app only when you choose to share a backup through another service.</Text><Text className="mt-3 text-sm leading-6 text-sub">Deleting the app may remove local data. Export a backup first if you want to keep it. Clear all data in Settings removes local study data and preferences.</Text><Pressable onPress={() => void Linking.openURL(PRIVACY_URL)} accessibilityRole="link" className="mt-3 min-h-11 justify-center"><Text className="font-bold text-teal">Read the full Privacy Policy</Text></Pressable></Card><Card className="mb-4"><Text className="text-lg font-bold text-ink">Study disclaimer</Text><Text className="mt-2 text-sm leading-6 text-sub">Kwagi organizes study material that you create. It is not an official source of academic, medical, legal, financial, or professional advice. Check facts against your instructors, syllabus, textbooks, and current institutional guidance. Quiz results and streaks do not guarantee grades, certification, or professional competence.</Text><Text className="mt-3 text-xs text-muted">Effective July 18, 2026</Text></Card><Card><Text className="text-lg font-bold text-ink">Support</Text><Text className="mt-2 text-sm leading-6 text-sub">Report app problems without sharing private notes or backup files.</Text><Pressable onPress={() => void Linking.openURL(SUPPORT_URL)} accessibilityRole="link" className="mt-3 min-h-11 justify-center"><Text className="font-bold text-teal">Open Kwagi Support</Text></Pressable></Card></Container></ScrollView></Screen>; }
